# Exercise class1 : NumPy array and Indexing Slicing

In [1]:
import sys
sys.path.append("C:\\Users\\guilh\\OneDrive\\Documentos\\GitHub\\sistemasinteligentes")
import numpy as np
import pandas as pd
from src.si.data.dataset import Dataset
from src.io.csv_file import read_csv, write_csv 
from src.io.data_file import *

**1.1. In this exercise , we will use the iris dataset . Load the "iris.csv" using the appropriate method for this file type (use the new functions from the package).**

In [2]:
filename = r"C:\Users\guilh\OneDrive\Documentos\GitHub\sistemasinteligentes\datasets\iris\iris.csv"

In [3]:
dataset=read_csv(filename, sep=",",features=True,label=True)

**1.2) Select the penultimate independent variable. What is the dimension of the resulting array?**


In [4]:
penultimo=dataset.X[:,-2]
print("Dimension:",penultimo.shape[0])

Dimension: 150


**1.3) Select the last 10 samples from the iris dataset. What is the mean of the last 10 samples for each independent variable/feature?**

In [5]:
last_10=dataset.X[-10:,:]
print(last_10)

[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]


In [6]:
mean_per_feature = np.mean(last_10, axis=0)
# indicar a media por cada feature
features_names=dataset.features[:]
mean_dict={features_names[i]:mean_per_feature[i] for i in range(len(features_names))}
print(mean_dict)

{'sepal_length': 6.450000000000001, 'sepal_width': 3.0300000000000002, 'petal_length': 5.33, 'petal_width': 2.17}


**1.4) Select all samples from the dataset with values less than or equal to 6 for all independent variables/features. How many samples do you obtain?**

In [7]:
dados = dataset.X[:,:]
condicao = (dados <= 6).all(axis=1) # para ir buscar apenas [] e poder fazer o resto, caso contrario aparece [[]]
soma = condicao.sum()
print("Obtained samples: ", soma)

Obtained samples:  89


**1.5) Select all samples with a class/label differentfrom 'Iris setosa'. How many samples do you obtain?**


In [8]:
novo=dataset.y
total=np.sum(novo!="Iris-setosa")
print("Obtained samples:", total)

Obtained samples: 100


**extra exercise**
Exploration even more the class dataset

In [9]:
X = np.array([[1, 2, 3],
              [4, 5, np.nan],
              [7, np.nan, 9]])
y = np.array([0, 1, 0])
features = ['feature_1', 'feature_2', 'feature_3']
label = 'target'

dataset = Dataset(X, y, features, label)
print("Shape:", dataset.shape())  # Deve retornar (3, 3)
print("Has Label:", dataset.has_label())  # Deve retornar True
print("Classes:", dataset.get_classes())  # Deve retornar [0 1]
print("Mean:", dataset.get_mean())  # Deve retornar [4. 5. 6.]
print("Variance:", dataset.get_variance())  
print("Median:", dataset.get_median())  # Deve retornar [4. 5. 6.]
print("Max:", dataset.get_max())  # Deve retornar [7. 8. 9.]
print("Min:", dataset.get_min())  # Deve retornar [1. 2. 3.]
summary_df = dataset.summary()
print("Summary:")
print(summary_df)
#removed_indices = dataset.dropna()
#print("dataset,Indices removidos:", removed_indices)  # Deve retornar os índices das linhas com valores NaN
#print("Shape após a remoção de NaNs:", dataset.shape())  # Deve retornar a nova forma após a remoção
strategy = "value"
dataset_filled_value = dataset.fill_na(strategy)
print(dataset_filled_value.X)
print(dataset.remove_by_index(0))
print(dataset.X,dataset.y)

Shape: (3, 3)
Has Label: True
Classes: [0 1]
Mean: [4.  3.5 6. ]
Variance: [6.   2.25 9.  ]
Median: [4.  3.5 6. ]
Max: [7. 5. 9.]
Min: [1. 2. 3.]
Summary:
          feature_1  feature_2  feature_3
mean            4.0       3.50        6.0
variance        6.0       2.25        9.0
median          4.0       3.50        6.0
max             7.0       5.00        9.0
min             1.0       2.00        3.0
[[1.         2.         3.        ]
 [4.         5.         5.06420129]
 [7.         2.87754883 9.        ]]
[[4.         5.         5.06420129]
 [7.         2.87754883 9.        ]] [1 0]
